### PR TITLE
Display conversion ratio between two units

### LINKED ISSUE #27: Show the conversion ratio
A child cannot easily learn the unit conversion ratios, because they are not shown.

### PR DESCRIPTION
**Pull request by nswarup14**
Fixes #27 

**Changes**
1) `activity.py`

**Updates**
1) Add a `Gtk.Label` to show the conversion ratio between units, below entry widget.

Tested on Ubuntu 18.04 and Sugar v0.114

### CODE REVIEW

**Comment by Hrishi1999** [comment]
Tested. Works as expected.

**Comment by quozl** [comment]
tmp

**Comment by quozl** [comment]
Conversion ratio display was merged in https://github.com/sugarlabs/convert/pull/30

**Comment by nswarup14** [comment]
@quozl 
I did not understand why this branch was closed.
#30 did not include the conversion ratio.

**Comment by quozl** [comment]
Oh, I see now.  Thanks.  Given that other pull requests have merged and another is due to merge soon, how do you propose to proceed?

**Comment by nswarup14** [comment]
@quozl 
Thanks!

The PR of redesign has been merged and PR of preserving dimensions and units is due to merge soon. However, the latter PR would not affect this in anyway.

I would rebase the present commits on top of PR #30 and continue to work from there.

Would that be alright?

**Comment by quozl** [comment]
Thanks.  Please rebase from the new _master_, and open a new pull request.

**Comment by nswarup14** [comment]
@quozl
Yes, I shall do so immediately. I had already rebased it till #30.
I shall make a new PR soon.

>

**Pull request closed without merging**
