### PR TITLE
Fix Runtime errors/Gtk3 port

### PR DESCRIPTION
**Pull request by chimosky**
Completed Gtk3 port
Fix import error

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Tested.  Good progress.  Still doesn't work quite right, but at least it doesn't fail to start.

**Comment by chimosky** [comment]
Thanks...i noticed, I'll see what i can do.
The author should tell the default behaviour of the buttons
- [ ] Button on the top left should show quantity being converted from, once clicked and not reset.
- [ ] Button on the right should do the same as button on the left.
- [ ] Incremental button should increase the selected quantity.

**Comment by quozl** [comment]
The author is Cristhofer Travieso.  But don't bother them prematurely; it should be enough to read the code, and test the GTK+ 2 version of the activity from git history.  See https://github.com/sugarlabs/convert/commit/66531be069200c354fc58fc07a9084aef20b1bee for the code before the port to GTK+ 3.

**Comment by chimosky** [comment]
Thanks.

**Pull request merged**
